swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    post:
      description: Creates new account
      operationId: createAccount
      parameters:
        - name: user
          in: body
          description: user to add to the database
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NewUser"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  # /token:
  #   get:
  #     description: gets token to authenticate user
  #     operationId: tokenCheck
  #     parameters:
  #       - name: cookie
  #         in: header
  #         description: gets token from req.swagger.user.cookie to authenticate user
  #         required: false
  #         schema:
  #           $ref: '#/definitions/Cookie'
  #     responses:
  #       "200":
  #         description: Success
  #         schema:
  #           # a pointer to a definition
  #           $ref: "#/definitions/Authenticated"
  #       # responses may fall through to errors
  #       default:
  #         description: Error
  #         schema:
  #           $ref: "#/definitions/ErrorResponse"
  /search:
    get:
      description: Returns a specific beer from brewerydb
      operationId: searchBeer
      parameters:
        - name: name
          in: query
          description: The name of the beer that was searched
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SearchBeer"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  SearchBeer:
    required:
      - id
      - beer_name
      - abv
      - ibu
      - label_url
      - description
      - type_name
    properties:
      id:
        type: string
      beer_name:
        type: string
      abv:
        type: string
      ibu:
        type: string
      label_url:
        type: string
      description:
        type: string
      type_name:
        type: string
  NewUser:
    required:
      - message
    properties:
      message:
        type: string
  User:
    type: object
    properties:
      first_name:
        type: string
        description: first name of new user
      last_name:
        type: string
        description: last name of new user
      username:
        type: string
        description: username
      email:
        type: string
        description: email
      password:
        type: string
        description: password
    required:
      - first_name
      - last_name
      - username
      - email
      - password
  # Cookie:
  #   type: header
  #   properties:
  #     token:
  #       type: int64
  #       description: cookie token
  # Authenticated:
  #   properties:
  #     message:
  #       type: boolean
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
